#!/bin/bash -e

action="$1"
oldversion="$2"

if [ "$action" != configure ]; then
    exit 0
fi

echo Ramdisk installed to /usr/share/kernel/
mkdir -p /usr/share/kernel
update-initramfs -tc -kgemini.cpio.gz -v -b /usr/share/kernel

update-gemian-boot-image
