#!/bin/bash

stowaway=""
boot=""
root_vg=""
root_lv=""
cmdline=$(</proc/cmdline)

if [[ "$cmdline" =~ ^(.*)bootpartition\=([a-z0-9]*)(.*)$ ]];
then
  boot="${BASH_REMATCH[2]}"
fi

if [[ "$cmdline" =~ ^(.*)stowaways_os\=([a-z0-9]*)(.*)$ ]];
then
  stowaway="${BASH_REMATCH[2]}"
fi

if [[ "$cmdline" =~ ^(.*)root_vg\=([a-z0-9]*)(.*)$ ]];
then
  root_vg="${BASH_REMATCH[2]}"
fi

if [[ "$cmdline" =~ ^(.*)root_lv\=([a-z0-9]*)(.*)$ ]];
then
  root_lv="${BASH_REMATCH[2]}"
fi

if [ -z "$stowaway" ] && [ -z "$root_lv" ]
then
  mkbootimg --kernel /usr/share/kernel/Image.gz-dtb --ramdisk /usr/share/kernel/initrd.img-gemini.cpio.gz --base 0x40080000 --second_offset 0x00e80000 --cmdline "bootopt=64S3,32N2,64N2 log_buf_len=4M" --kernel_offset 0x00000000 --ramdisk_offset 0x04f80000 --tags_offset 0x03f80000 --pagesize 2048 -o /usr/share/kernel/linux-boot.img
fi

if [ -n "$stowaway" ]
then
  mkbootimg --kernel /usr/share/kernel/Image.gz-dtb --ramdisk /usr/share/kernel/initrd.img-gemini.cpio.gz --base 0x40080000 --second_offset 0x00e80000 --cmdline "bootopt=64S3,32N2,64N2 log_buf_len=4M stowaways_os=${stowaway}" --kernel_offset 0x00000000 --ramdisk_offset 0x04f80000 --tags_offset 0x03f80000 --pagesize 2048 -o /usr/share/kernel/linux-boot-stowaways-${stowaway}.img
fi

if [ -n "$root_lv" ] && [ -z "$root_vg" ]
then
  mkbootimg --kernel /usr/share/kernel/Image.gz-dtb --ramdisk /usr/share/kernel/initrd.img-gemini.cpio.gz --base 0x40080000 --second_offset 0x00e80000 --cmdline "bootopt=64S3,32N2,64N2 log_buf_len=4M root_lv=${root_lv}" --kernel_offset 0x00000000 --ramdisk_offset 0x04f80000 --tags_offset 0x03f80000 --pagesize 2048 -o /usr/share/kernel/linux-boot-lvm-${root_lv}.img
fi

if [ -n "$root_lv" ] && [ -n "$root_vg" ]
then
  mkbootimg --kernel /usr/share/kernel/Image.gz-dtb --ramdisk /usr/share/kernel/initrd.img-gemini.cpio.gz --base 0x40080000 --second_offset 0x00e80000 --cmdline "bootopt=64S3,32N2,64N2 log_buf_len=4M root_vg=${root_vg} root_lv=${root_lv}" --kernel_offset 0x00000000 --ramdisk_offset 0x04f80000 --tags_offset 0x03f80000 --pagesize 2048 -o /usr/share/kernel/linux-boot-lvm-${root_vg}-${root_lv}.img
fi

echo ""
echo "Kernel images installed to /usr/share/kernel/"
if [ -z "$boot" ]
then
  echo "Note: Old boot loader detected, flying blind, please carefully select kernel and boot partition as appropriate to your setup, taking particular reference to the boot time keys you hold to select gemian"
  boot="boot2"
fi

echo "You need to write the correct kernel to the correct boot partition based upon your boot configuration:"

if [ -z "$stowaway" ] && [ -z "$root_lv" ]
then
  echo "eg: sudo dd if=/usr/share/kernel/linux-boot.img of=/dev/disk/by-partlabel/${boot}"
fi

if [ -n "$stowaway" ]
then
  echo "or: sudo dd if=/usr/share/kernel/linux-boot-stowaways-${stowaway}.img of=/dev/disk/by-partlabel/${boot}"
fi

if [ -n "$root_lv" ] && [ -z "$root_vg" ]
then
  echo "or: sudo dd if=/usr/share/kernel/linux-boot-lvm-${root_lv}.img of=/dev/disk/by-partlabel/${boot}"
fi

if [ -n "$root_lv" ] && [ -n "$root_vg" ]
then
  echo "or: sudo dd if=/usr/share/kernel/linux-boot-lvm-${root_vg}-${root_lv}.img of=/dev/disk/by-partlabel/${boot}"
fi

echo "After writing the kernel image a reboot is necessary to use the new kernel."
echo ""
